version: "3.9"
services: 
  web:
    build: .
    ports:
      - 8443:8443
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/padelante
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=padelante
#    volumes:
#      - ./postgres:/var/lib/postgresql/data